export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-error': '#ffffff',
        'surface-variant': '#d3e4fe',
        'tertiary': '#825100',
        'on-tertiary-container': '#fffbff',
        'outline': '#727785',
        'on-primary': '#ffffff',
        'inverse-primary': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'surface-container-highest': '#d3e4fe',
        'on-secondary': '#ffffff',
        'surface-container': '#e5eeff',
        'on-surface': '#0b1c30',
        'surface-dim': '#cbdbf5',
        'primary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#4edea3',
        'secondary': '#006c49',
        'error-container': '#ffdad6',
        'on-surface-variant': '#424754',
        'surface-container-low': '#eff4ff',
        'surface-bright': '#f8f9ff',
        'on-primary-container': '#fefcff',
        'primary-container': '#2170e4',
        'on-tertiary': '#ffffff',
        'inverse-surface': '#213145',
        'on-primary-fixed-variant': '#004395',
        'tertiary-fixed-dim': '#ffb95f',
        'surface-container-lowest': '#ffffff',
        'on-error-container': '#93000a',
        'surface-container-high': '#dce9ff',
        'surface': '#f8f9ff',
        'error': '#ba1a1a',
        'on-secondary-container': '#00714d',
        'tertiary-fixed': '#ffddb8',
        'outline-variant': '#c2c6d6',
        'on-secondary-fixed': '#002113',
        'inverse-on-surface': '#eaf1ff',
        'primary-fixed-dim': '#adc6ff',
        'on-background': '#0b1c30',
        'tertiary-container': '#a36700',
        'on-tertiary-fixed-variant': '#653e00',
        'on-secondary-fixed-variant': '#005236',
        'on-tertiary-fixed': '#2a1700',
        'primary': '#0058be',
        'secondary-container': '#6cf8bb',
        'surface-tint': '#005ac2',
        'secondary-fixed': '#6ffbbe',
        'background': '#f8f9ff'
      },
      fontFamily: {
        'body-lg': ['Inter'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'caption': ['Inter'],
        'title-md': ['Inter'],
        'display-lg': ['Inter'],
        'headline-lg': ['Inter'],
        'headline-lg-mobile': ['Inter'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' }],
      },
    },
  },
  plugins: [],
};
